### ISSUE TITLE
Edit button on each list item does not work. 

### ISSUE THREAD

**Issue by Yagnadat-Talakola** [gordonmzhu/practical-javascript#2]
Found out that the button-id on each Edit button is of the form `'edit-'` and in the event handler on line 129 we are looking for `event.target.id.includes('editTodo')` which will never find a match and returns false. We can circumvent this by doing: `event.target.id.includes('edit')`. This works as desired.

**Comment by gordonmzhu** [comment]
Thanks for pointing this out @Yagnadat-Talakola. I pushed a new version yesterday that fixes this issue.
